// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
#pragma multi_compile _ _MAIN_LIGHT_SHADOWS
#pragma multi_compile _ _MAIN_LIGHT_SHADOWS_CASCADE
#pragma multi_compile _ _SHADOWS_SOFT
// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"
#include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Shadows.hlsl"
#include "SH.hlsl"

struct Surfel
{
    float3 position;
    float3 normal;
    float3 albedo;
    float skyMask;
};
RWStructuredBuffer<Surfel>_surfels;
RWStructuredBuffer<float3>_surfelRadiance;

float _skyLightIntensity;
float4 _probePos;

RWStructuredBuffer<int> _coefficientSH9;  

int _indexInProbeVolume;
RWStructuredBuffer<int> _coefficientVoxel;  
StructuredBuffer<int> _lastFrameCoefficientVoxel;
float _GIIntensity;

//volume 参数
float _coefficientVoxelGridSize;
float4 _coefficientVoxelCorner;
float4 _coefficientVoxelSize;

[numthreads(32,16,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

    uint surfelIndex = id.y * 32 + id.x;
    Surfel surfel = _surfels[surfelIndex];

    Light mainLight = GetMainLight();
    //下面计算周围光时用lanbert就行
    float4 shadowCoord = TransformWorldToShadowCoord(surfel.position);
    float atten = SampleShadowmap(
        TEXTURE2D_ARGS(_MainLightShadowmapTexture, sampler_MainLightShadowmapTexture), 
        shadowCoord, 
        GetMainLightShadowSamplingData(), 
        GetMainLightShadowParams(), 
        false
    );

    float NdotL = saturate(dot(surfel.normal, mainLight.direction));
    float3 radiance = (surfel.albedo / PI) * mainLight.color * NdotL * atten * (1.0 - surfel.skyMask);

    float3 dir = normalize(surfel.position - _probePos.xyz);
    float3 skyColor = SAMPLE_TEXTURECUBE_LOD(_GlossyEnvironmentCubeMap, sampler_GlossyEnvironmentCubeMap, dir, 0).rgb;
    radiance += skyColor * surfel.skyMask * _skyLightIntensity;  

    //复用上一帧
 
    if (_indexInProbeVolume >= 0)
    {
        float3 historyRadiance = SampleSHVoxel(
                float4(surfel.position, 1.0),
                surfel.albedo,
                surfel.normal,
                _lastFrameCoefficientVoxel,
                _coefficientVoxelGridSize,
                _coefficientVoxelCorner,
                _coefficientVoxelSize
            );

        radiance += historyRadiance * _GIIntensity;
    }

    //SH
    const float N = 32 * 16;
    float3 c[9];
    c[0] = SH(0,  0, dir) * radiance * 4.0 * PI / N;
    c[1] = SH(1, -1, dir) * radiance * 4.0 * PI / N;
    c[2] = SH(1,  0, dir) * radiance * 4.0 * PI / N;
    c[3] = SH(1,  1, dir) * radiance * 4.0 * PI / N;
    c[4] = SH(2, -2, dir) * radiance * 4.0 * PI / N;
    c[5] = SH(2, -1, dir) * radiance * 4.0 * PI / N;
    c[6] = SH(2,  0, dir) * radiance * 4.0 * PI / N;
    c[7] = SH(2,  1, dir) * radiance * 4.0 * PI / N;
    c[8] = SH(2,  2, dir) * radiance * 4.0 * PI / N;
    //所有线程都要进行叠加，把c0到c9放到 _coefficientSH9中，但是由于所有线程都操作同一个 所以要加锁
    for(int i=0; i<9; i++)
    {
        InterlockedAdd(_coefficientSH9[i*3+0], EncodeFloatToInt(c[i].x));
        InterlockedAdd(_coefficientSH9[i*3+1], EncodeFloatToInt(c[i].y));
        InterlockedAdd(_coefficientSH9[i*3+2], EncodeFloatToInt(c[i].z));
    }
    //存
    if(_indexInProbeVolume >= 0)
    {
        const int coefficientByteSize = 27;
        int offset = _indexInProbeVolume * coefficientByteSize;
        for(int i=0; i<9; i++)
        {
            InterlockedAdd(_coefficientVoxel[offset + i*3+0], EncodeFloatToInt(c[i].x));
            InterlockedAdd(_coefficientVoxel[offset + i*3+1], EncodeFloatToInt(c[i].y));
            InterlockedAdd(_coefficientVoxel[offset + i*3+2], EncodeFloatToInt(c[i].z));
        }
    }
    //输出用于测试
    _surfelRadiance[surfelIndex] = radiance;
}
